version: '3'

services:
  payload:
    image: node:bookworm
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm ci && npm run payload seed && npm run dev"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: sea_catering
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5433'

volumes:
  pgdata:
  node_modules:
